version: '3'
services:
  asset-manager-backend:
    build:
      context: ./AssetManagerBackend
      dockerfile: Dockerfile
    ports:
      - "61150:80"

  asset-manager-frontend:
    build:
      context: ./AssetManagerFrontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
